//
//  UIColor+UNTAdditions.h
//
//  Generated by Zeplin on 11/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (UNTAdditions)

+ (UIColor *)unt_whiteColor;
+ (UIColor *)unt_whiteTwoColor;
+ (UIColor *)unt_blackColor;
+ (UIColor *)unt_warmGreyColor;
+ (UIColor *)unt_whiteThreeColor;
+ (UIColor *)unt_greyishBrownColor;
+ (UIColor *)unt_greyishColor;
+ (UIColor *)unt_dustyOrangeColor;
+ (UIColor *)unt_seafoamBlueColor;

@end
