//
//  UIColor+UNTAdditions.m
//
//  Generated by Zeplin on 11/4/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+UNTAdditions.h"

@implementation UIColor (UNTAdditions)

+ (UIColor *)unt_whiteColor {
	return [UIColor colorWithWhite:241.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_whiteTwoColor {
	return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_blackColor {
	return [UIColor colorWithWhite:36.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_warmGreyColor {
	return [UIColor colorWithWhite:155.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_whiteThreeColor {
	return [UIColor colorWithWhite:232.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_greyishBrownColor {
	return [UIColor colorWithWhite:74.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_greyishColor {
	return [UIColor colorWithRed:173.0f / 255.0f green:172.0f / 255.0f blue:172.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_dustyOrangeColor {
	return [UIColor colorWithRed:245.0f / 255.0f green:118.0f / 255.0f blue:35.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)unt_seafoamBlueColor {
	return [UIColor colorWithRed:98.0f / 255.0f green:199.0f / 255.0f blue:164.0f / 255.0f alpha:1.0f];
}

@end
