//
//  UIColor+AVRColors.m
//
//  Generated by Zeplin on 11/2/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+AVRColors.h"

@implementation UIColor (AVRColors)

+ (UIColor *)avr_warmGreyColor {
    return [UIColor colorWithWhite:146.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)avr_white80Color {
    return [UIColor colorWithWhite:255.0f / 255.0f alpha:0.8f];
}

+ (UIColor *)avr_squashColor {
    return [UIColor colorWithRed:245.0f / 255.0f green:166.0f / 255.0f blue:35.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)avr_blackColor {
    return [UIColor colorWithWhite:3.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)avr_whiteColor {
    return [UIColor colorWithWhite:216.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)avr_steelColor {
    return [UIColor colorWithRed:142.0f / 255.0f green:142.0f / 255.0f blue:147.0f / 255.0f alpha:1.0f];
}



+ (UIColor *)ai_whiteColor {
    return [UIColor colorWithWhite:244.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)ai_whiteTwoColor {
    return [UIColor colorWithWhite:221.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)ai_whiteThreeColor {
    return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)ai_greenyBlueColor {
    return [UIColor colorWithRed:61.0f / 255.0f green:185.0f / 255.0f blue:187.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)ai_warmGreyColor {
    return [UIColor colorWithWhite:111.0f / 255.0f alpha:1.0f];
}

+ (UIImage *)imageWithColor:(UIColor *)color {
    CGRect rect = CGRectMake(0.0f, 0.0f, 1.0f, 1.0f);
    UIGraphicsBeginImageContext(rect.size);
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    CGContextSetFillColorWithColor(context, [color CGColor]);
    CGContextFillRect(context, rect);
    
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}

+ (UIImage *)imageWithColor:(UIColor *)color with:(CGRect)rect
{
    
    UIGraphicsBeginImageContext(rect.size);
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    CGContextSetFillColorWithColor(context, [color CGColor]);
    CGContextFillRect(context, rect);
    
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    
    return image;
}


@end
