//
//  UIColor+AVRColors.h
//
//  Generated by Zeplin on 11/2/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIColor (AVRColors)

+ (UIColor *)avr_warmGreyColor;
+ (UIColor *)avr_white80Color;
+ (UIColor *)avr_squashColor;
+ (UIColor *)avr_blackColor;
+ (UIColor *)avr_whiteColor;
+ (UIColor *)avr_steelColor;
+ (UIColor *)avr_scarlet1Color;
+ (UIColor *)ai_warmGreyColor;
+ (UIColor *)ai_whiteColor;

+ (UIColor *)ai_whiteTwoColor;

+ (UIColor *)ai_whiteThreeColor;
+ (UIColor *)ai_greenyBlueColor;


+ (UIImage *)imageWithColor:(UIColor *)color;
+ (UIImage *)imageWithColor:(UIColor *)color with:(CGRect)rect;
@end
